# Usa una imagen base de Node.js
FROM node:16.13.2

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia los archivos de configuración del backend (package-lock.json y package.json)
COPY package*.json ./

# Instala las dependencias del backend
RUN npm install

# Copia el resto de los archivos del backend
COPY . ./

# Expón el puerto en el que tu aplicación escucha
EXPOSE 3000

# Ejecuta el comando para iniciar tu aplicación
CMD ["node", "src/MqttClient.js"]
