# Usa una imagen base de Node.js
FROM node:16.13.2

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app/Meteorology

# Copia el archivo app.js desde el directorio src al directorio de trabajo del contenedor
COPY package*.json ./

# Instala las dependencias de la aplicación
RUN npm install

COPY . .

# Expone el puerto 5173 para acceder a la aplicación (si es necesario)
EXPOSE 5173

# Define el comando de inicio para ejecutar la aplicación
CMD ["npm", "run", "dev"]
