# Usa la imagen base de Node.js versión 14
FROM node:14

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app/Meteorology

# Copia el archivo app.js desde el directorio src al directorio de trabajo del contenedor
COPY Meteorology/package*.json ./

# Instala las dependencias de la aplicación
RUN npm install

COPY Meteorology .

# Expone el puerto 3000 para acceder a la aplicación (si es necesario)
EXPOSE 3000

# Define el comando de inicio para ejecutar la aplicación
CMD ["npm", "run", "dev"]


